version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/ec2-user/client
  - source: /node_modules
    destination: /home/ec2-user/client/node_modules
hooks:
  AfterInstall:
    - location: script/after-deploy
      timeout: 180
