version: 0.0
os: linux
files:
  - source: /public
    destination: /home/ec2-user/client/
  - source: /node_modules
    destination: /home/ec2-user/client/node_modules
hooks:
  AfterInstall:
    - location: scripts/after-deploy
      timeout: 180
